### ISSUE TITLE
NoHostAvailableException invokation

### ISSUE THREAD

**Issue by Dark0096** [graphene-monitoring/graphene#39]
I encounter a lot of stack traces like below:

```
2020-01-03 09:57:50.269 ERROR 1 --- [ool-3-thread-64] c.g.w.s.data.CassandraDataStoreHandler   : com.datastax.driver.core.exceptions.NoHostAvailableException: All host(s) tried for query failed (tried: /x.x.x.x:9042 (com.datastax.driver.core.exceptions.BusyPoolException: [/x.x.x.x:9042] Pool is busy (no available connection and the queue has reached its max size 256)), internal-common-metric-cassandra-v6-1266747549.ap-northeast-2.elb.amazonaws.com/x.x.x.x:9042 (com.datastax.driver.core.exceptions.BusyPoolException: [internal-common-metric-cassandra-v6-1266747549.ap-northeast-2.elb.amazonaws.com/x.x.x.x:9042] Pool is busy (no available connection and the queue has reached its max size 256)))

com.datastax.driver.core.exceptions.NoHostAvailableException: All host(s) tried for query failed (tried: /x.x.x.x:9042 (com.datastax.driver.core.exceptions.BusyPoolException: [/x.x.x.x:9042] Pool is busy (no available connection and the queue has reached its max size 256)), internal-common-metric-cassandra-v6-1266747549.ap-northeast-2.elb.amazonaws.com/x.x.x.x:9042 (com.datastax.driver.core.exceptions.BusyPoolException: [internal-common-metric-cassandra-v6-1266747549.ap-northeast-2.elb.amazonaws.com/10.56.21.66:9042] Pool is busy (no available connection and the queue has reached its max size 256)))
        at com.datastax.driver.core.RequestHandler.reportNoMoreHosts(RequestHandler.java:283) ~[cassandra-driver-core-3.8.0.jar!/:na]
        at com.datastax.driver.core.RequestHandler.access$1200(RequestHandler.java:61) ~[cassandra-driver-core-3.8.0.jar!/:na]
        at com.datastax.driver.core.RequestHandler$SpeculativeExecution.findNextHostAndQuery(RequestHandler.java:375) ~[cassandra-driver-core-3.8.0.jar!/:na]
        at com.datastax.driver.core.RequestHandler$SpeculativeExecution$1.onFailure(RequestHandler.java:444) ~[cassandra-driver-core-3.8.0.jar!/:na]
        at com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:1015) ~[guava-28.1-jre.jar!/:na]
        at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:30) ~[guava-28.1-jre.jar!/:na]
        at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:1137) ~[guava-28.1-jre.jar!/:na]
        at com.google.common.util.concurrent.AbstractFuture.addListener(AbstractFuture.java:707) ~[guava-28.1-jre.jar!/:na]
        at com.google.common.util.concurrent.AbstractFuture$TrustedFuture.addListener(AbstractFuture.java:112) ~[guava-28.1-jre.jar!/:na]
        at com.google.common.util.concurrent.Futures.addCallback(Futures.java:996) ~[guava-28.1-jre.jar!/:na]
        at com.datastax.driver.core.GuavaCompatibility.addCallback(GuavaCompatibility.java:112) ~[cassandra-driver-core-3.8.0.jar!/:na]
        at com.datastax.driver.core.GuavaCompatibility.addCallback(GuavaCompatibility.java:100) ~[cassandra-driver-core-3.8.0.jar!/:na]
        at com.datastax.driver.core.RequestHandler$SpeculativeExecution.query(RequestHandler.java:400) ~[cassandra-driver-core-3.8.0.jar!/:na]
        at com.datastax.driver.core.RequestHandler$SpeculativeExecution.findNextHostAndQuery(RequestHandler.java:359) ~[cassandra-driver-core-3.8.0.jar!/:na]
        at com.datastax.driver.core.RequestHandler$SpeculativeExecution$1.onFailure(RequestHandler.java:444) ~[cassandra-driver-core-3.8.0.jar!/:na]
        at com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:1015) ~[guava-28.1-jre.jar!/:na]
        at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:30) ~[guava-28.1-jre.jar!/:na]
        at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:1137) ~[guava-28.1-jre.jar!/:na]
        at com.google.common.util.concurrent.AbstractFuture.addListener(AbstractFuture.java:707) ~[guava-28.1-jre.jar!/:na]
        at com.google.common.util.concurrent.AbstractFuture$TrustedFuture.addListener(AbstractFuture.java:112) ~[guava-28.1-jre.jar!/:na]
        at com.google.common.util.concurrent.Futures.addCallback(Futures.java:996) ~[guava-28.1-jre.jar!/:na]
        at com.datastax.driver.core.GuavaCompatibility.addCallback(GuavaCompatibility.java:112) ~[cassandra-driver-core-3.8.0.jar!/:na]
        at com.datastax.driver.core.GuavaCompatibility.addCallback(GuavaCompatibility.java:100) ~[cassandra-driver-core-3.8.0.jar!/:na]
        at com.datastax.driver.core.RequestHandler$SpeculativeExecution.query(RequestHandler.java:400) ~[cassandra-driver-core-3.8.0.jar!/:na]
        at com.datastax.driver.core.RequestHandler$SpeculativeExecution.findNextHostAndQuery(RequestHandler.java:359) ~[cassandra-driver-core-3.8.0.jar!/:na]
        at com.datastax.driver.core.RequestHandler.startNewExecution(RequestHandler.java:139) ~[cassandra-driver-core-3.8.0.jar!/:na]
        at com.datastax.driver.core.RequestHandler.sendRequest(RequestHandler.java:121) ~[cassandra-driver-core-3.8.0.jar!/:na]
        at com.datastax.driver.core.SessionManager.execute(SessionManager.java:696) ~[cassandra-driver-core-3.8.0.jar!/:na]
        at com.datastax.driver.core.SessionManager.executeAsync(SessionManager.java:142) ~[cassandra-driver-core-3.8.0.jar!/:na]
        at com.graphene.writer.store.data.CassandraDataStoreHandler.handle(CassandraDataStoreHandler.kt:55) ~[classes!/:na]
        at com.graphene.writer.processor.GrapheneProcessor.process(GrapheneProcessor.kt:36) ~[classes!/:na]
        at com.graphene.writer.processor.GrapheneProcessor$$FastClassBySpringCGLIB$$c2ee8a20.invoke(<generated>) ~[classes!/:na]
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.2.1.RELEASE.jar!/:5.2.1.RELEASE]
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:769) ~[spring-aop-5.2.1.RELEASE.jar!/:5.2.1.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.2.1.RELEASE.jar!/:5.2.1.RELEASE]
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747) ~[spring-aop-5.2.1.RELEASE.jar!/:5.2.1.RELEASE]
        at org.springframework.aop.interceptor.AsyncExecutionInterceptor.lambda$invoke$0(AsyncExecutionInterceptor.java:115) ~[spring-aop-5.2.1.RELEASE.jar!/:5.2.1.RELEASE]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_222]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_222]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_222]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_222]
```

**Comment by Dark0096** [comment]
This issue resolved PR [#40]
